import pandas as pd 
import numpy as np

class Vertex:
    """ The Vertex class is designed to represent a single vertex from a label file generated by FreeSurfer. 
    It stores details about the vertex such as:
    --- Index: A unique identifier for the vertex.
    --- Coordinates: The 3D spatial location (x, y, z) of the vertex.
    --- Visual Area: The functional area of the brain to which the vertex belongs.
    Additionally, the class provides a static method, load_vertices, which reads a label file and creates a 
    list of Vertex objects for a specified visual area, with an option to load only one vertex.""" 
        
    def __init__(self, index: int, x: float, y: float, z: float, visual_area: int):
        self.index = index                   # e.g. 14017 
        self.x = x                           # e.g. -10.072  
        self.y = y                           # e.g. -78.545
        self.z = z                           # e.g. 66.078 
        self.visual_area = visual_area       # e.g. 1

    def load_vertices(labels_path: str, visual_area: int, load_one=False):
        """
        Load vertices from the label file for a given visual area.
            Inputs: 
            --- Label: the path to the label file to load the vertices from.
            --- Visual Area: 1 for source area, 2 for target area
            --- Load One: if true, load only one vertex.
            Outputs:
            --- Vertex: a list of vertices objects loaded from the label file.
        """
        # Read the label file into a DataFrame 
        df = pd.read_csv(labels_path, header=None, skiprows=2, sep='\\s+') 
        # Filter the rows where the value in column 4 matched the value of visual area
        df_filtered = df[df[4] == visual_area]

        # Convert the filtered rows into a vertex object 
        # This expression takes filtered rows from the DataFrame, interprets each row as a set of 
        # arguments for the Vertex constructor, and builds a NumPy array of Vertex objects
        vertices = np.array([Vertex(*i) for i in df_filtered.itertuples(index=False)])
        if load_one:
            vertex = vertices[0]
            print(f"Loaded one Vertex: Index = {vertex.index}, X = {vertex.x}, Y = {vertex.y}, Z = {vertex.z}, Visual Area = {vertex.visual_area}")
            return [vertex]
            
        # Print how many vertices were loaded for the specific visual area
        print(f"Loaded {len(vertices)} vertices from Visual Area {visual_area} from {labels_path}.")
        
        return vertices