from imports import *

class Vertex:
    """ The Vertex class represents a single vertex from a label file generated by FreeSurfer. 
    It supports both 'manualdelin' and 'benson' atlases.
    """ 
        
    def __init__(self, index: int, x: float, y: float, z: float, visual_area: float):
        self.index = index                   
        self.x = x                           
        self.y = y                           
        self.z = z                           
        self.visual_area = visual_area       

    @staticmethod
    def load_vertices(labels_path: str, visual_area: int, atlas: str):
        """
        Load vertices from the label file for a given visual area and atlas type.
        
        Parameters: 
            labels_path (str): Path to the label file.
            visual_area (int): Visual area number (V1=1, V2=2, V3=3).
            atlas (str): 'manualdelin' or 'benson'.
        
        Returns:
            List or array of Vertex objects.
        """
        df = pd.read_csv(labels_path, header=None, skiprows=2, sep='\\s+') 
        
        if atlas == 'manual':
            df_filtered = df[df[4] == visual_area]
        elif atlas == 'benson':
            # For Benson atlas, visual areas are 1.0, 2.0, 3.0 (as floats)
            df_filtered = df[np.isclose(df[4], float(visual_area))]
        else:
            raise ValueError("Atlas type must be either 'manualdelin' or 'benson'.")

        vertices = np.array([Vertex(*i) for i in df_filtered.itertuples(index=False)])

        print(f"Loaded {len(vertices)} vertices from V{visual_area} using {atlas} atlas from {labels_path}.")
        return vertices